### PR TITLE
Fix 'SyntaxWarning: invalid escape sequence \s'

### PR DESCRIPTION
**Pull request by dummydata**
simple fix to quiet syntax warnings

### CODE REVIEW

**Comment by jtyr** [comment]
Thanks for pointing this out. I think it would be better use [raw string](https://docs.python.org/3/library/re.html) instead of double backslashes.

**Comment by dummydata** [comment]
Agreed, raw strings are better. The patch has been updated

**Comment by jtyr** [comment]
Thanks for your contribution, @dummydata!

**Comment by dummydata** [comment]
> Thanks for your contribution, @dummydata!

Thank you for a very useful module/role @jtyr!

**Pull request merged**
